config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users do
    resources :calendars
    resources :slots
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
    has_one :UserCalendar
    # attr_accessor :email, :token
end

app/models/user_calendar.rb
class UserCalendar < ApplicationRecord
  belongs_to :user
  MIN_SLOT_SIZE = 15

  # attr_accessor :preference

  enum week_day: [ :Sunday, :Monday, :Tuesday, :Wednesday, :Thursday, :Friday, :Saturday ]

  # Params:
  # buffer: integer in mins
  # per_day_slots: [
  #   {
  #     start: integer in mins
  #     end: integer in mins
  #   }
    
  # ]
  # week_days_available: array of integer, eg: [1,2,3,4,5] => Monday to Friday
  # time_zone: 
  def available_day_range
    preferences["availablility"]["per_day"]
  end

  def time_zone
    preferences["time_zone"]
  end

  def buffer
    preferences["buffer"]
  end

  def week_days_available
    preferences["availablility"]["per_week"]
  end

  def preferences
    JSON.parse(self.preference)
  end

  def self.create_preference (buffer, per_day_slots, week_days_available, time_zone)
    {
      buffer: buffer, 
      availablility: {
        per_day: per_day_slots,
        
        per_week: week_days_available
      },
      time_zone: time_zone

    }.to_json
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/calendars_controller.rb
class CalendarsController < ApplicationController
  before_action :set_user_calendar, only: [:show, :edit, :update, :destroy]

  # GET /user_calendars
  # GET /user_calendars.json
  def index
    @user_calendars = UserCalendar.where(user_id: params[:user_id])
  end

  # GET /user_calendars/1
  # GET /user_calendars/1.json
  def show
  end

  # GET /user_calendars/new
  def new
    @user_calendar = UserCalendar.new
  end

  # GET /user_calendars/1/edit
  def edit
  end

  # POST /user_calendars
  # POST /user_calendars.json
  def create
    user_calendars_count = UserCalendar.where(user_id: params[:user_id]).count
    if(user_calendars_count > 0)
      redirect_to user_calendars_url, notice: 'User calendar already exists.'
      return
    end
    @user_calendar = UserCalendar.new(user_calendar_params)

    respond_to do |format|
      if @user_calendar.save
        format.html { redirect_to user_calendar_path(@user_calendar), notice: 'User calendar was successfully created.' }
        format.json { render :show, status: :created, location: @user_calendar }
      else
        format.html { render :new }
        format.json { render json: @user_calendar.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_calendars/1
  # PATCH/PUT /user_calendars/1.json
  def update
    respond_to do |format|
      if @user_calendar.update(user_calendar_params)
        format.html { redirect_to @user_calendar, notice: 'User calendar was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_calendar }
      else
        format.html { render :edit }
        format.json { render json: @user_calendar.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_calendars/1
  # DELETE /user_calendars/1.json
  def destroy
    @user_calendar.destroy
    respond_to do |format|
      format.html { redirect_to user_calendars_url, notice: 'User calendar was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_calendar
      @user_calendar = UserCalendar.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_calendar_params
      user_calendar = params[:user_calendar]
      {

        user_id: params[:user_id], 
        preference: UserCalendar.create_preference(
          user_calendar[:buffer].to_i,
          JSON.parse(user_calendar[:per_day_slots]),
          JSON.parse(user_calendar[:week_days_available]),
          user_calendar[:time_zone])
      }
    end
end

app/controllers/slots_controller.rb
class SlotsController < ApplicationController

  # GET /user_calendars
  # GET /user_calendars.json
  def index
    @user_slots = slots_service.slots(user)
  end

  # POST /user_calendars
  # POST /user_calendars.json
  def create
    @user_calendar = UserCalendar.new(user_calendar_params)

    respond_to do |format|
      if @user_calendar.save
        format.html { redirect_to @user_calendar, notice: 'User calendar was successfully created.' }
        format.json { render :show, status: :created, location: @user_calendar }
      else
        format.html { render :new }
        format.json { render json: @user_calendar.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def slots_service
    @slots_service ||= SlotsService.new
  end

  def user
    @user ||= User.find(params[:user_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :token)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendars_helper.rb
module CalendarsHelper
end

app/helpers/user_slots_helper.rb
module UserSlotsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/calendars/_form.html.erb
<%= form_with(model: [user_calendar], local: true) do |form| %>
  <% if user_calendar.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user_calendar.errors.count, "error") %> prohibited this user_calendar from being saved:</h2>

      <ul>
      <% user_calendar.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :buffer %>
    <%= form.number_field :buffer %>
  </div>

  <div class="field">
    <%= form.label :per_day_slots %>
    <%= form.text_field :per_day_slots %>
  </div>

  <div class="field">
    <%= form.label :week_days_available %>
    <%= form.text_field :week_days_available %>
  </div>

  <div class="field">
    <%= form.label :time_zone %>
    <%= form.time_zone_select( :time_zone, nil, default: "Pacific Time (US & Canada)", :class => "col-xs-8") %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/calendars/edit.html.erb
<h1>Editing User Calendar</h1>

<%= render 'form', user_calendar: @user_calendar %>

<%= link_to 'Show', @user_calendar %> |
<%= link_to 'Back', user_calendar_path %>

app/views/calendars/index.html.erb
<p id="notice"><%= notice %></p>

<h1>User Calendars</h1>

<table>
  <thead> 
    <tr>
      <th>ID</th>
      <th>User</th>
      <th>Preference</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_calendars.each do |user_calendar| %>
      <tr>
        <td><%= user_calendar.id %></td>
        <td><%= user_calendar.user_id %></td>
        <td><%= user_calendar.preference %></td>
        <td><%= link_to 'Show', user_calendar_path(id: user_calendar.id) %></td>
        <td><%= link_to 'Edit', edit_user_calendar_path(id: user_calendar.id) %></td>
        <td><%= link_to 'Destroy', user_calendar_path(id: user_calendar.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User Calendar', new_user_calendar_path %>

app/views/calendars/new.html.erb
<h1>New User Calendar</h1>

<%= render 'form', user_calendar: @user_calendar %>

<%= link_to 'Back', user_calendars_path %>

app/views/calendars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @user_calendar.user_id %>
</p>

<p>
  <strong>preference:</strong>
  <%= @user_calendar.preference %>
</p>


<%= link_to 'Edit', edit_user_calendar_path(@user_calendar) %> |
<%= link_to 'Back', user_calendar_path(@user_calendar)  %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Calendar</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/slots/_form.html.erb
<%= form_with(model: [, user_calendar], local: true) do |form| %>
  <% if user_calendar.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user_calendar.errors.count, "error") %> prohibited this user_calendar from being saved:</h2>

      <ul>
      <% user_calendar.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :offset %>
    <%= form.number_field :offset %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :start %>
    <%= form.datetime_select :start %>
  </div>

  <div class="field">
    <%= form.label :end %>
    <%= form.datetime_select :end %>
  </div>

  <div class="field">
    <%= form.label :stols %>
    <%= form.text_field :stols %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/slots/edit.html.erb
<h1>Editing User Calendar</h1>

<%= render 'form', user_calendar: @user_calendar %>

<%= link_to 'Show', @user_calendar %> |
<%= link_to 'Back', _user_calendars_path %>

app/views/slots/index.html.erb
<p id="notice"><%= notice %></p>

<h1>User Calendars</h1>

<table>
  <thead> 
    <tr>
      <th>ID</th>
      <th> from</th>
      <th> to</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_slots.each_with_index do |slot,index| %>
      <tr>
        <td><%= index %></td>
        <td><%= slot[:from] %></td>
        <td><%= slot[:to] %></td>

      </tr>
    <% end %>
    
  </tbody>
</table>
<br>

app/views/slots/new.html.erb
<h1>New User Calendar</h1>

<%= render 'form', user_calendar: @user_calendar %>

<%= link_to 'Back', _user_calendars_path %>

app/views/slots/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @user_calendar.user_id %>
</p>

<p>
  <strong>Offset:</strong>
  <%= @user_calendar.offset %>
</p>

<p>
  <strong>Name:</strong>
  <%= @user_calendar.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user_calendar.email %>
</p>

<p>
  <strong>Start:</strong>
  <%= @user_calendar.start %>
</p>

<p>
  <strong>End:</strong>
  <%= @user_calendar.end %>
</p>

<p>
  <strong>Stols:</strong>
  <%= @user_calendar.stols %>
</p>

<%= link_to 'Edit', edit_user_calendar_path(@user_calendar) %> |
<%= link_to 'Back', _user_calendars_path %>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :token %>
    <%= form.text_field :token %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Token</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.token %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Token:</strong>
  <%= @user.token %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>